FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    bash \
    curl \
    libpng-dev \
    libjpeg-turbo-dev \
    libzip-dev \
    oniguruma-dev \
    zip \
    unzip \
    git

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip opcache

COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html/backend

EXPOSE 9000
CMD ["php-fpm"]
