server {
    listen 80;
    server_name pontofacilrh.com.br www.pontofacilrh.com.br;
    root /var/www/html/dist;
    index index.html;
    client_max_body_size 50M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api {
        fastcgi_pass app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param REQUEST_URI $request_uri;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
